# Generated by Django 3.0.3 on 2020-03-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_auto_20200303_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='act_date',
            field=models.DateTimeField(verbose_name='active_date'),
        ),
    ]
